spring:
  application:
    name: travel-agent
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ai
      username: root
      password: Yhh20031123
    postgres:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://rm-cn-e4v4c3oz50009s5o.rwlb.rds.aliyuncs.com:5432/ai_agent
      username: my_user
      password: Yhh20031123
  #    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ai
#    username: root
#    password: Yhh20031123

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    dashscope:
      api-key: sk-ceca398bd46b4b2684d30625ef19b8ae
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json


search-api:
  api-key: bixX4AuUdYFUes1Q1XhEEhnz
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yhh.travelagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
